[package]
name = "sptm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"

[profile.release]
panic = 'abort'
strip = true
lto = true
opt-level = 2
